---
- name: Ping servers
  hosts: all
  become: true

  tasks:
   - name: ping all database servers
     ping:

   - name: install nginx web servers
     apt:
      name: nginx
      state: present

   - name: confirm installation by starting the nginx service
     service:
      name: nginx
      state: started